postgres:
  image: postgres
  ports:
     -  "5432:5432"
  environment:
     - "constraint:flocker-node==2"
     - "POSTGRES_USER=flocker"
     - "POSTGRES_PASSWORD=flocker"
     - "PGDATA=/var/lib/postgresql/data"
  volume_driver: flocker
  volumes:
     - 'postgres:/var/lib/postgresql/data'
